services:
  app:
    build: .
    ports:
      - "10000:10000"
    volumes:
      - .:/usr/src/app
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:10000/health || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
