services:
  api:
    build: .
    container_name: tradextr
    ports:
      - "10000:10000"
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:10000/health || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
