services:
  api:
    container_name: tradextr
    image: python:3.12.3-bookworm
    environment:
      - PATH=/usr/src/app/.venv/bin:$PATH
    ports:
      - "10000:10000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: python src/main.py
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:10000/health || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
