services:
  api:
    build: .
    container_name: tradextr
    ports:
      - "10000:10000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "10000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 3s
